-- Flyway migration: V1__create_core_tables.sql
-- MySQL 8.0 compatible version

CREATE TABLE ROLE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(4000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USER_ACCOUNT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(255),
    PASSWORD_HASH VARCHAR(4000) NOT NULL,
    ENABLED TINYINT(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP NULL,
    VERSION BIGINT DEFAULT 0
);

CREATE TABLE USER_ROLE (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(ID),
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

CREATE TABLE BOT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BOT_KEY VARCHAR(255) NOT NULL UNIQUE,
    ENABLED TINYINT(1) DEFAULT 1,
    OWNER_ID BIGINT,
    CONFIG LONGTEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT FK_BOT_OWNER FOREIGN KEY (OWNER_ID) REFERENCES USER_ACCOUNT(ID)
);

CREATE TABLE FLOW (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOT_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(50),
    DEFINITION LONGTEXT,
    ENABLED TINYINT(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT FK_FLOW_BOT FOREIGN KEY (BOT_ID) REFERENCES BOT(ID)
);

CREATE TABLE INTENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOT_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONFIDENCE_THRESHOLD DECIMAL(5,4) DEFAULT 0.50,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_INTENT_BOT FOREIGN KEY (BOT_ID) REFERENCES BOT(ID)
);

CREATE TABLE UTTERANCE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INTENT_ID BIGINT NOT NULL,
    TEXT VARCHAR(4000) NOT NULL,
    CONSTRAINT FK_UTTER_INTENT FOREIGN KEY (INTENT_ID) REFERENCES INTENT(ID)
);

CREATE TABLE SESSION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOT_ID BIGINT NOT NULL,
    USER_ID BIGINT,
    STATE LONGTEXT,
    STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ENDED_AT TIMESTAMP NULL,
    CONSTRAINT FK_SESSION_BOT FOREIGN KEY (BOT_ID) REFERENCES BOT(ID),
    CONSTRAINT FK_SESSION_USER FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(ID)
);

CREATE TABLE MESSAGE_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID BIGINT NOT NULL,
    SENDER VARCHAR(50),
    MESSAGE_TEXT LONGTEXT,
    METADATA LONGTEXT,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MSG_SESSION FOREIGN KEY (SESSION_ID) REFERENCES SESSION(ID)
);

CREATE TABLE METRIC (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOT_ID BIGINT,
    METRIC_TYPE VARCHAR(100),
    METRIC_VALUE DECIMAL(19,2),
    CAPTURED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_USER_USERNAME ON USER_ACCOUNT(USERNAME);
CREATE INDEX IDX_BOT_OWNER ON BOT(OWNER_ID);
CREATE INDEX IDX_SESSION_BOT ON SESSION(BOT_ID);

INSERT INTO ROLE (NAME, DESCRIPTION) VALUES ('ADMIN', 'Administrador do sistema');
INSERT INTO ROLE (NAME, DESCRIPTION) VALUES ('GESTOR', 'Gestor de Bots');
INSERT INTO ROLE (NAME, DESCRIPTION) VALUES ('USUARIO', 'Usuário padrão');

